CREATE DATABASE StudentScholarship;

USE StudentScholarship;
create table STUDENT (
STUDENT_ID INT PRIMARY KEY,
FIRST_NAME VARCHAR(20),
SECOND_NAME VARCHAR(20),
GPA DECIMAL(5,2),
ENROLLMENT_DATE datetime,
MAJOR VARCHAR(20)
);

 INSERT INTO STUDENT (STUDENT_ID,FIRST_NAME,SECOND_NAME,GPA,ENROLLMENT_DATE,MAJOR) VALUE
 ('201','Shivansh','Mahajan','8.79','2021-09-01 09:30:000','CSE'),
 ('202','Umesh','Sharma','8.44','2021-09-01 08:30:000','MATH'),
 ('203','Rakesh','Kumar','5.60','2021-09-01 10:00:000','BIO'),
 ('204','Radha','Sharma','9.20','2021-09-01 12:45:000','CHE'),
 ('205','Kush','Kumar','7.85','2021-09-01 08:30:000','PHY'),
 ('206','Prem','Chopra','9.56','2021-09-01 09:24:000','HIS'),
 ('207','Pankaj','Vats','9.78','2021-09-01 02:30:000','ENG'),
 ('208','Navleen','Kaur','7.00','2021-09-01 06:30:000','MATH');
 
SELECT *FROM STUDENT;
 
 
CREATE TABLE Program (
  STUDENT_REF_ID INT PRIMARY KEY,
  PROGRAMME_NAME VARCHAR(50),
  PROGRAMME_START_DATE DATETIME,
  FOREIGN KEY (STUDENT_REF_ID) REFERENCES STUDENT(STUDENT_ID)
) ENGINE=InnoDB;


INSERT INTO Program  value
 ('201','CSE','2021-09-01 00:00:000'),
 ('202','MATH','2021-09-01 00:00:000'),
 ('208','MATH','2021-09-01 00:00:000'),
 ('205','PHY','2021-09-01 00:00:000'),
 ('204','CHE','2021-09-01 00:00:000'),
 ('207','PSY','2021-09-01 00:00:000'),
('206','HIS','2021-09-01 00:00:000'),
 ('203','BIO','2021-09-01 00:00:000');

 SELECT *FROM Program ; 
 
 
create table Scholarship(
  STUDENT_REF_ID int primary key,
Scholarship_Amount int,
Scholarship_Date datetime,
FOREIGN KEY (STUDENT_REF_ID) REFERENCES Program (STUDENT_REF_ID)
)ENGINE=InnoDB;

insert into Scholarship values
(201,5000,'2021-10-15 00:00:000'),
(202,4500,'2022-08-18 00:00:000'),
(203,3000,'2022-01-25 00:00:000'),
(204,4000,'2021-10-15 00:00:000');

select * from Scholarship;



#Answer to the question no:01

SELECT UPPER(FIRST_NAME) AS STUDENT_NAME FROM STUDENT;


##Answer to the question no:02

SELECT DISTINCT MAJOR FROM STUDENT;
SELECT MAJOR FROM STUDENT GROUP BY(MAJOR);


#Answer to the question no:03

SELECT SUBSTRING(FIRST_NAME,1,3) FROM STUDENT;

#Answer to the question no:04

SELECT INSTR(LOWER(FIRST_NAME),'a') FROM STUDENT WHERE FIRST_NAME='Shivansh';

#Answer to the question no:05

SELECT DISTINCT MAJOR,LENGTH(MAJOR) FROM STUDENT;

#Answer to the question no:06

SELECT REPLACE(FIRST_NAME,'a','A') FROM STUDENT;

#Answer to the question no:07

SELECT CONCAT(FIRST_NAME," ",SECOND_NAME) AS COMPLETE_NAME FROM STUDENT;

#Answer to the question no:08

SELECT * FROM STUDENT ORDER BY FIRST_NAME,MAJOR DESC;

#Answer to the question no:09

SELECT * FROM STUDENT WHERE FIRST_NAME IN('Prem','Shivansh');

#Answer to the question no:10

SELECT * FROM STUDENT WHERE FIRST_NAME NOT IN('Prem','Shivansh');

#Answer to the question no:11

SELECT * FROM STUDENT WHERE FIRST_NAME LIKE '%a';

#Answer to the question no:12

SELECT * FROM STUDENT WHERE FIRST_NAME LIKE '____a';

#Answer to the question no:13

SELECT * FROM STUDENT WHERE GPA BETWEEN 9.00 AND 9.99;

#Answer to the question no:14

SELECT MAJOR,COUNT(*) AS TOTAL_COUNT FROM STUDENT WHERE MAJOR='CSE';

#Answer to the question no:15

SELECT CONCAT(FIRST_NAME,' ',SECOND_NAME) AS FULL_NAME FROM STUDENT WHERE GPA BETWEEN 8.5 AND 9.5;

#Answer to the question no:16

SELECT MAJOR,COUNT(MAJOR) FROM STUDENT GROUP BY MAJOR ORDER BY COUNT(MAJOR) DESC;

#Answer to the question no:17

SELECT
STUDENT.FIRST_NAME,
STUDENT.SECOND_NAME,
SCHOLARSHIP.SCHOLARSHIP_AMOUNT,
SCHOLARSHIP.SCHOLARSHIP_DATE
FROM
STUDENT
INNER JOIN
SCHOLARSHIP ON  STUDENT.STUDENT_ID=SCHOLARSHIP.STUDENT_REF_ID;

#Answer to the question no:18

SELECT * FROM STUDENT WHERE STUDENT_ID % 2 !=0;

#Answer to the question no:19

SELECT * FROM STUDENT WHERE STUDENT_ID % 2=0;

#Answer to the question no:20

SELECT STUDENT.FIRST_NAME,STUDENT.SECOND_NAME,
SCHOLARSHIP.SCHOLARSHIP_AMOUNT,
SCHOLARSHIP.SCHOLARSHIP_DATE FROM STUDENT LEFT JOIN
SCHOLARSHIP ON STUDENT.STUDENT_ID=SCHOLARSHIP.STUDENT_REF_ID;

#Answer to the question no:21

SELECT * FROM STUDENT ORDER BY GPA DESC LIMIT 5;


#Answer to the question no:22

SELECT * FROM STUDENT ORDER BY GPA DESC LIMIT 4,1;

#Answer to the question no:23

SELECT * FROM STUDENT S1
WHERE 4=
(SELECT COUNT(DISTINCT(S2.GPA))
FROM STUDENT S2
WHERE S2.GPA>=S1.GPA
);

#Answer to the question no:24

SELECT S1.* FROM STUDENT S1, STUDENT S2 WHERE S1.GPA=S2.GPA AND
S1.STUDENT_ID !=S2.STUDENT_ID;

#Answer to the question no:25

SELECT MAX(GPA) FROM STUDENT WHERE GPA NOT IN(SELECT MAX(GPA) FROM STUDENT);

#Answer to the question no:26

SELECT * FROM STUDENT
UNION ALL 
SELECT * FROM STUDENT ORDER BY STUDENT_ID;


#Answer to the question no:27

SELECT STUDENT_ID FROM STUDENT
WHERE STUDENT_ID NOT IN(SELECT STUDENT_REF_ID FROM SCHOLARSHIP);


#Answer to the question no:28

SELECT * FROM STUDENT
LIMIT (SELECT FLOOR(COUNT(*)/2) FROM STUDENT);


#Answer to the question no:29

SELECT MAJOR, COUNT(MAJOR) AS MAJOR_COUNT FROM STUDENT GROUP BY MAJOR HAVING COUNT(MAJOR)<4;

#Answer to the question no:30

SELECT MAJOR,COUNT(MAJOR) AS ALL_MAJOR FROM STUDENT GROUP BY MAJOR;


#Answer to the question no:31

SELECT * FROM STUDENT WHERE STUDENT_ID=(SELECT MAX(STUDENT_ID) FROM STUDENT);


#Answer to the question no:32

SELECT * FROM STUDENT WHERE STUDENT_ID=(SELECT MIN(STUDENT_ID) FROM STUDENT);


#Answer to the question no:33


SELECT * FROM(
SELECT * FROM STUDENT ORDER BY STUDENT_ID DESC LIMIT 5)
AS SUBQUERY ORDER BY STUDENT_ID; 

#Answer to the question no:34

SELECT DISTINCT GPA FROM STUDENT S1 
WHERE 3>= (SELECT COUNT(DISTINCT GPA) FROM STUDENT S2 WHERE S1.GPA <= S2.GPA)
ORDER BY S1.GPA DESC;


#Answer to the question no:35

SELECT DISTINCT GPA FROM STUDENT S1
WHERE 3>= (SELECT COUNT(DISTINCT GPA) FROM STUDENT S2 WHERE S1.GPA=S2.GPA)
ORDER BY S1.GPA;


#Answer to the question no:36

SELECT DISTINCT GPA FROM STUDENT S1
WHERE 5= (SELECT COUNT(DISTINCT GPA) FROM STUDENT S2 WHERE S1.GPA<=S2.GPA)
ORDER BY S1.GPA DESC;

#Answer to the question no:37

SELECT MAJOR, MAX(GPA) AS MAXGPA FROM STUDENT GROUP BY MAJOR;

#Answer to the question no:38

SELECT FIRST_NAME,GPA FROM STUDENT WHERE GPA = (SELECT MAX(GPA) FROM STUDENT);

#Answer to the question no:39

SELECT CURDATE();
SELECT NOW();


#Answer to the question no:40

CREATE TABLE CLONETABLE AS SELECT * FROM STUDENT;

SELECT * FROM CLONETABLE;

#Answer to the question no:41

SET SQL_SAFE_UPDATES = 0;

UPDATE STUDENT SET GPA=7.5 WHERE MAJOR='CSE';

#Answer to the question no:42

SELECT MAJOR, AVG(GPA) AS AVERAGE_GPA FROM STUDENT GROUP BY MAJOR;

#Answer to the question no:43
SELECT * FROM STUDENT ORDER BY GPA DESC LIMIT 3;

#Answer to the question no:44
SELECT MAJOR,COUNT(STUDENT_ID) AS HIGH_GPA_COUNT FROM STUDENT WHERE GPA>7.5
GROUP BY MAJOR;

#Answer to the question no:45


SELECT * FROM STUDENT 
WHERE GPA=(SELECT GPA FROM STUDENT WHERE STUDENT_ID=201);

